### ISSUE TITLE
Potentially none of the scripts working

### ISSUE THREAD

**Issue by johentsch** [MarkGotham/Taking-Form#4]
If someone tried to use, for example, `table2brackets.py` following the usage hint `Usage: python table2brackets.py <tableFile.csv> <outputFile.txt>`, they would get the following error: 

    ModuleNotFoundError: No module named 'markup'

This is not surprising as all the scripts seem to be loading scripts from the `markup` folder in which they reside themselves. Deleting the string `markup.` in the entire folder makes the scripts work at once.

**Comment by MarkGotham** [comment]
Many thanks for this @laserjeyes and apologies for only seeing it now.

This is now resolved. PRs always welcome.
